services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: unique_resources
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata18:/var/lib/postgresql/data
      - ./ddl-scripts/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
    mem_limit: 1500M
    mem_reservation: 1500M
    cpus: 0.5
    command: ["postgres", "-c", "log_statement=all"] # ???

  zipkin-db:
    image: mariadb:11.8.5
    container_name: zipkin-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=zipkin
      - MARIADB_PASSWORD=zipkin
      - MARIADB_USER=zipkin
    volumes:
      # 1. Mounts your storage volume
      - ./zipkin-db-data:/var/lib/mysql
      - ./ddl-scripts/init-zipkin.sql:/docker-entrypoint-initdb.d/init-zipkin.sql
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512M

  # Zipkin
  # http://127.0.0.1:9411/zipkin/
  zipkin:
    image: ghcr.io/openzipkin/zipkin:3.6.1
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-db
      - MYSQL_DB=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    ports:
      - "9411:9411"
    depends_on:
      - zipkin-db

volumes:
    zipkin-db-data: