
services:
  postgres-db:
    image: postgres:latest
    #container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: unique_resources
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata18:/var/lib/postgresql/data
      - ./ddl-scripts/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
    mem_limit: 1500M
    mem_reservation: 1500M
    cpus: 1.5
    command: ["postgres", "-c", "log_statement=all"] # ???
