include "application.conf"
include "local-cluster.conf"


#GRPC_PORT: 8080
#REQ_CONTACT_POINT_VAR: 2
#CONTACT_POINTS: 127.0.0.1,127.0.0.2


akka.remote.artery.canonical.port=2550
akka.remote.artery.canonical.hostname=127.0.0.2
akka.management.http.hostname=127.0.0.2


#akka.management.http.bind-hostname=127.0.0.2
#akka.remote.artery.bind.port=2550
#akka.remote.artery.bind.hostname=127.0.0.2