akka.management.cluster.bootstrap.contact-point-discovery {
  service-name = "resources"
  discovery-method = config
  # boostrap filters ports with the same IP assuming they are previous instances running on the same node
  # unless a port is specified
  port-name = "management"
  required-contact-point-nr = 2
  # config service discovery never changes
  stable-margin = 3 ms
  # bootstrap without all the nodes being up
  contact-with-all-contact-points = false
}

akka.discovery.config.services {
  "resources" {
    endpoints = [
      {host = "127.0.0.1", port = 8558}
      {host = "127.0.0.2", port = 8558}
    ]
  }
}

akka.cluster.split-brain-resolver {
  active-strategy = keep-majority
}

akka.persistence.r2dbc.connection-factory.user=root
akka.persistence.r2dbc.connection-factory.database=unique_resources
akka.persistence.r2dbc.connection-factory.host=127.0.0.1
akka.persistence.r2dbc.connection-factory.password=secret
akka.persistence.r2dbc.connection-factory.ssl.enabled=off

akka.management.cluster.bootstrap.contact-point-discovery.discovery-method=config