akka {
  persistence {
    max-concurrent-recoveries = 32 #50
    journal {
      plugin = "akka.persistence.r2dbc.journal"
    }
    snapshot-store {
      plugin = "akka.persistence.r2dbc.snapshot"
    }

    state.plugin = "akka.persistence.r2dbc.state"

    #r2dbc.connection-factory = ${akka.persistence.r2dbc.postgres}
    #r2dbc.connection-factory {
    #  host = "localhost"
    #  database = "testdb"
    #  user = "postgres"
    #  password = "password"
    #}

    r2dbc {
      # yugabyte or postgres
      dialect = "postgres"

      connection-factory {
        driver = "postgres"


        host = ${?DB_HOST}

        port = 5432
        port = ${?DB_PORT}

        database = ${?DB_NAME}
        user = ${?DB_USER}
        password = ${?DB_PASSWORD}
        ssl {
          enabled = off
          #enabled = on
          #mode = require
        }
        max-size = 7  # to avoid hitting the db connection limits
      }

      journal {
        class = "akka.persistence.r2dbc.journal.R2dbcJournal"

        # Enable this to reduce latency of eventsBySlices. The persisted events will be
        # published as Akka messages and consumed directly by running eventsBySlices
        # queries. Tradeoff is more CPU and network resources that are used. The events
        # must still be retrieved from the database, but at a lower polling frequency,
        # because delivery of published messages are not guaranteed.
        publish-events = on

        #publish-events-dynamic.throughput-threshold = 400
      }

      query {
        class = "akka.persistence.r2dbc.query.R2dbcReadJournalProvider"

        # When live queries return no results or <= 10% of buffer-size, the next query
        # to db will be delayed for this duration.
        # When the number of rows from previous query is >= 90% of buffer-size, the next
        # query will be emitted immediately.
        # Otherwise, between 10% - 90% of buffer-size, the next query will be delayed
        # for half of this duration.
        refresh-interval = 2s #3s

        # Live queries read events up to this duration from the current database time.
        behind-current-time = 100 millis

        # When journal publish-events is enabled a best effort deduplication can be enabled by setting
        # this property to the size of the deduplication buffer in the `eventsBySlices` query.
        # It keeps track of this number of entries and 5000 is recommended capacity. The drawback
        # of enabling this is that when the sequence numbers received via publish-events are out of sync
        # after some error scenarios it will take longer to receive those events, since it will rely on
        # the backtracking queries.
        deduplicate-capacity = 1024
      }

      # We trust that system time will not move backward for two subsequent persists from the same entity.
      # See also https://github.com/yugabyte/yugabyte-db/issues/10996
      db-timestamp-monotonic-increasing = on

      # Workaround of https://github.com/yugabyte/yugabyte-db/issues/10995
      # FIXME: This property should be removed when the Yugabyte issue has been resolved.
      # Note that query.behind-current-time can probably be decreased if we can use db time.
      use-app-timestamp = on
    }
  }

  projection.r2dbc {

    offset-store {
      # only timestamp based offsets
      offset-table = ""
    }


    #
    number-of-slices = 4
  }
}
